### ISSUE TITLE
API for configuring drivers

### ISSUE THREAD

**Issue by tanner0101** [vapor/jobs#29]
There's a bit of manual work currently required to get a valid `JobsPersistanceLayer`. We should provide some convenience APIs for this like [FluentKit](https://github.com/vapor/fluent-kit/blob/master/Sources/FluentKit/Database/Databases.swift) does. 

Each driver can extend those convenience APIs with functions for supplying the required credentials.

**Comment by tanner0101** [comment]
Perhaps we could utilize `JobsConfiguration`,  something like this would be nice:

```swift
s.extend(JobsConfiguration.self) { configuration, container in
    let job = try ExecutorJob(container)
    configuration.add(job)
    configuration.configureRedis(hostname: ..., port: ...)
}
```

**Comment by mcdappdev** [comment]
But with that wouldn't the main `jobs` package have to know that `Redis` exists?

**Comment by tanner0101** [comment]
@mcdappdev no, `JobsConfiguration` would hold just a `JobsPersistanceLayer`, then `JobsRedisDriver` would extend `JobsConfiguration` to add that method

**Comment by mcdappdev** [comment]
Ahh I see. That could work nicely! Let's plan on doing that.

**Comment by tanner0101** [comment]
We need to make sure that we use the provider (or other means) to properly cleanup any connection pools that we create
