### ISSUE TITLE
Run in Application's EventLoopGroup for Vapor 3

### ISSUE THREAD

**Issue by Igor-Palaguta** [vapor/jobs#34]
It is cool if there is way to customize event loop group for version 0.2.7. Like in new version to reuse application's event loops group

Under hobby account in heroku there is a limit 20 postgres connections for all workers. And JobCommand creates `MultiThreadedEventLoopGroup(numberOfThreads: System.coreCount)` and every thread creates own connections as I understand correctly. So this limit is easy to reach currently

**Comment by mcdappdev** [comment]
That's a good point. We should make it customizable.

**Comment by mcdappdev** [comment]
FYI - this will be fixed for v1

**Comment by Igor-Palaguta** [comment]
v1 is shipped with Vapor 4?
Cool if for Vapor 3 it will also work

**Comment by mcdappdev** [comment]
Right now V1 is targeting Vapor 4, so no, it won't work in Vapor 3. If I get some time later this week or next week though I can make a patch for Vapor 3.
