### ISSUE TITLE
make testScheduledJob faster

### ISSUE THREAD

**Issue by tanner0101** [vapor/jobs#37]
Right now the smallest unit of time scheduled jobs support is a minute. This makes waiting for the scheduled jobs test to run pretty annoying. 

Maybe we should add seconds or a `schedule(at:Date)` method? This would allow us to run the tests a lot faster and could be useful to the end user.

**Comment by mcdappdev** [comment]
Yeah, this is an annoying pain point right now. Adding another smaller unit seems like overkill since I'm not sure people will be scheduling things at that increment (although maybe they will?).

**Comment by tanner0101** [comment]
Yeah that's why I was thinking maybe `schedule(at:)` for one-off jobs? Then in tests we could schedule a one-off job ~5 seconds in the future.

**Comment by mcdappdev** [comment]
Yeah I think that’s the way to do it. That’s a helpful feature to have anyway
