### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by VineFiner** [vapor/jobs#50]
Hi, Can add an executable target to show sending emails every hour?

**Comment by mcdappdev** [comment]
Hi there, I'm not 100% positive what's being asked here but if you're inquiring about whether or not it's possible to send an email every hour, then yes, that's definitely possible :)

**Comment by VineFiner** [comment]
Hello, is there a demo?
https://github.com/vapor/api-template/tree/kitchen-sink
Me run jobs
Email can be printed, but how to print it regularly?
I did not find the documentation.
Sorry, this may not be an issue.  But I look at the iOS library, they have demos, which is very convenient.

**Comment by mcdappdev** [comment]
Right now there is no complete documentation as that will be published when it is tagged 1.0. The best reference is from the recent forum update: https://forums.swift.org/t/whats-new-in-vapor-4/31832

**Comment by VineFiner** [comment]
Okay thank you
