### ISSUE TITLE
In Process Jobs... start Scheduled with no ScheduledJobs

### ISSUE THREAD

**Issue by khoogheem** [vapor/jobs#55]
If I use the example app.. or my own and try the command:
`try JobsCommand(application: app, scheduled: true).startScheduledJobs()`

It produces the error `Assertion failed: JobsCommand did not shutdown before deinit: file`
If there is no call to: `app.jobs.schedule` prior to calling the `. startScheduledJobs()`

I get why that is.. but I wonder if there is a better way to handle this.. such as a precondition to give a warning that no jobs of type `ScheduledJob` have been put onto the schedule

**Comment by mcdappdev** [comment]
Fixed via #57 thank you!
