### ISSUE TITLE
Supplying an Application instance when dequeuing a job

### ISSUE THREAD

**Issue by Andrewangeta** [vapor/jobs#60]
It would be advantageous to have access to an instance of `Application` when dequeueing a job. 
Maybe having it added as a property on the `JobContext`

```swift
func dequeue(_ context: JobContext, _ payload: SomeJob) -> EventLoopFuture<Void> {
    context.application.someService.....
}
```

**Comment by tanner0101** [comment]
As a workaround, `app.jobs.configuration` has a `userInfo` dict that you can put whatever you need into. Then you can access that from `context.configuration`

**Comment by Andrewangeta** [comment]
Sounds good.
